[skl] Fix multidimensional array code generation defect
Details

  The compiler was generating wrong code for heap-based dynamic
  arrays, and data-based static arrays.

  To investigate the issue, the following changes were made to
  SKLST.ArrayDesc:

  o The generically named 'n' field was renamed to 'len'.  Searching
    the sources for uses of this 'n' proved to be difficult.  This
    field is now only used for the length of statically-sized arrays.

    The dimension number for dynamic arrays was never fully
    implemented because it was never neeed; so this declared use is
    discarded.

  o The generically named 'offset' field is renamed to the more unique
    'lenTDOffs' to also facilitate finding uses throughout the
    compiler.

  This was caused by two defects.

   1. Inconsistent treatment of the length of an array dimension.

      o For statically-sized arrays, the length of the array is
        consistently used through the compiler, because the length is
        stored in the symbol table.

      o For dynamically-sized arrays, the maximum index -- not the
        length -- of each dimension is kept in the internal type
        descriptor that is present before the array's data on the
        heap.

        These bound values must be turned into lengths by adding one
        before use.  But this addition must only occur for heap-based
        arrays, not for statically-sized arrays.

      o For open array parameters, the bound rather than the length is
        passed on the stack.  When using LEN() for open arrays, the
        bound must be adjusted by adding 1.

   2. The CGL.Iregix mode when getting the length of an array.

      In SKLCGH.GetArrayDimLen(), when the mode of 'x' was CGL.Iregix
      (base register + scaled index register), the compiler was
      incorrectly using the index register in the code generated to
      load the length of the array dimension.  Now the CGL.Iregix mode
      is converted into CGL.Iregi to use only the base register, and
      the constant offset to the length in the internal descriptor.

Testing

  skl-build -j 10
  ./scripts/skl-compile-os-skl
  ./scripts/skl-compile-os-skl  (to ensure Obj & Sym stability)
  ./scripts/skl-test-compiler
  ./scripts/skl-test-system
  ./scripts/skl-test-modules

diff --git a/scripts/skl-test-compiler b/scripts/skl-test-compiler
--- a/scripts/skl-test-compiler
+++ b/scripts/skl-test-compiler
@@ -1,5 +1,5 @@
 #!/bin/bash
-# Copyright (c) 2021, 2022 Logic Magicians Software
+# Copyright (c) 2021, 2022, 2023 Logic Magicians Software
 #
 # Compile OS using x86-based SKL-targeting compiler.
 #
@@ -17,9 +17,9 @@ function compile()
     local cmd="skl-skl-oc ${pathname}";
     local output="$(skl-build-path)/${module}.compile.out"
 
-    echo "Executing: ${cmd}";
+    echo "Compiling: ${cmd}";
     if ! ${cmd} 2>&1 >"${output}"; then
-        echo "**** Compiling '${module} failed";
+        echo -e "**** Compiling '${module} failed\n\n";
         return 1;
     fi;
     return 0;
@@ -36,17 +36,17 @@ function run()
 
     echo "Executing: ${cmd}";
     if [[ ${value} == *manual* ]] ; then # Substring check
-        echo "**** Module '${module} is only run manually";
+        echo -e "**** Module '${module} is only run manually\n\n";
     elif [[ "${value}" == *pass* ]] ; then
-        if ! ${cmd} 2>&1 >"${output}"; then
-            echo "**** $?: Module '${module} expected to pass, but did not.";
+        if ! (${cmd} 2>&1) >"${output}"; then
+            echo -e "**** $?: Module '${module} expected to pass, but did not.\n\n";
         fi;
     elif [[ "${value}" == *fail* ]] ; then
-        if ${cmd} 2>&1 >"${output}"; then
-            echo "**** $?: Module '${module} expected to fail, but did not.";
+        if (${cmd} 2>&1) >"${output}"; then
+            echo -e "**** $?: Module '${module} expected to fail, but did not.\n\n";
         fi;
     else
-        echo "No recognizable arguments for '${module}' in '${value}'";
+        echo -e "No recognizable arguments for '${module}' in '${value}'\n\n";
         false;
     fi;
 }
